# Generated by Django 2.2.9 on 2020-05-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nomenclature_type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('RAW_MATERIAL', 'RAW_MATERIAL')], max_length=15)),
                ('kind_of_nomenclature', models.CharField(choices=[('PEN_FORM', 'PEN_FORM'), ('PEN_REFILL', 'PEN_REFILL'), ('PENCIL_FORM', 'PENCIL_FORM'), ('PEN', 'PEN'), ('PENCIL', 'PENCIL'), ('PAINT', 'PAINT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('date_of_manufacture', models.DateTimeField()),
                ('receiving_date', models.DateTimeField()),
                ('cell', models.ManyToManyField(blank=True, related_name='product', to='warehouse.Cell')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.Nomenclature')),
            ],
        ),
    ]
