# Generated by Django 2.2.9 on 2020-05-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('clientele_type', models.CharField(choices=[('CLIENT', 'CLIENT'), ('PROVIDER', 'PROVIDER')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='b0f22d4f-984c-427f-b', max_length=20)),
                ('date_of_sending', models.DateTimeField(auto_now_add=True)),
                ('first_check_passed', models.BooleanField(default=False)),
                ('second_check_passed', models.BooleanField(default=False)),
                ('waybill_type', models.CharField(choices=[('SUPPLY', 'SUPPLY'), ('SELLING', 'SELLING')], default='SUPPLY', max_length=15)),
                ('clientele_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientele_participant_waybill', to='waybills.Clientele')),
                ('firm_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_participant_waybill', to='waybills.Clientele')),
                ('products', models.ManyToManyField(related_name='product_waybill', to='products.Product')),
            ],
        ),
    ]
