# Generated by Django 2.2.10 on 2020-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='number',
            field=models.CharField(default='8281293236898', max_length=20),
        ),
    ]
