# Generated by Django 2.2.10 on 2020-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0002_auto_20200502_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientele',
            name='clientele_type',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='firm_participant',
        ),
        migrations.AlterField(
            model_name='waybill',
            name='number',
            field=models.CharField(default='1007287294865', max_length=20),
        ),
    ]
